// Fonts
import { Anton, Roboto } from "next/font/google";
// Styles
import "./globals.scss";
// Public & Assets

// React/Next Functions

// Context

// Components
import Header from "@/containers/header/header.container.jsx";
import Footer from "@/containers/footer/footer.container.jsx";

const anton = Anton({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-anton",
});
const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export async function generateMetadata() {
  return {
    title: "Template",
    description: "Generated by create next app",
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="cs">
      <body
        className={`${anton.variable} ${roboto.variable}`}
        suppressHydrationWarning={true}
      >
        <Header variant="leftsettings-centerlogo-rightmenu" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
