// Fonts
import { Anton, Roboto } from 'next/font/google'
// Styles
import "./globals.scss";
// Context

// Components


const anton = Anton({weight: '400', subsets: ['latin'], variable: '--font-anton'});
const roboto = Roboto({weight: '400', subsets: ['latin'], variable: '--font-roboto'});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="cz">
      <body className={`${anton.variable} ${roboto.variable}`} >
        {children}
      </body>
    </html>
  );
}
