// Fonts
import { Inter, Work_Sans } from "next/font/google";
// Styles
import "./globals.scss";
// Public & Assets

// React/Next Functions

// Context

// Components
import Header from "@/containers/header/header.container.jsx";
import Footer from "@/containers/footer/footer.container.jsx";

const fontPrimary = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-1",
});
const fontSecondary = Work_Sans({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-2",
});

export async function generateMetadata() {
  return {
    title: "Template",
    description: "Generated by create next app",
  };
}

export default function RootLayout({ children }) {
  return (
    <html lang="cs">
      <body
        className={`${fontPrimary.variable} ${fontSecondary.variable}`}
        suppressHydrationWarning={true}
      >
        <Header variant="leftsettings-centerlogo-rightmenu" />
        {children}
        <Footer />
      </body>
    </html>
  );
}
